@startuml

top to bottom direction

class mastermind.views.ColorView {
    ~ write(): void
}
utils.WithConsoleView <|--- mastermind.views.ColorView

class mastermind.views.SecretCombinationView {
    ~ SecretCombinationView(PlayController)
    ~ writeln(): void
}
utils.WithConsoleView <|--- mastermind.views.SecretCombinationView
mastermind.views.SecretCombinationView ..> mastermind.views.MessageView
mastermind.views.SecretCombinationView --> mastermind.controllers.PlayController
mastermind.views.SecretCombinationView ..> mastermind.views.MessageView

class mastermind.views.ProposedCombinationView {
    ~ ProposedCombinationView(combination: ProposedCombination)
    ~ void write()
    ~ void read()
}

enum mastermind.views.MessageView {
    + ATTEMPTS
   	+ SECRET
   	+ RESUME
   	+ RESULT
   	+ PROPOSED_COMBINATION
   	+ TITLE
   	+ WINNER
   	+ LOOSER
    - message: String
    - MessageView(String)
}

class mastermind.views.Command {
    # playController: PlayController
    - title: String
    # Command(String, PlayController)
    # {abstract} execute(): void
    # {abstract} isActive(): boolean
    ~ getTitle(): String
}

class mastermind.views.RedoCommand {
    ~ RedoCommand(controller: PlayController)
}
mastermind.views.Command <|-- mastermind.views.RedoCommand

class mastermind.views.UndoCommand {
    ~ UndoCommand(controller: PlayController)
}
mastermind.views.Command <|-- mastermind.views.UndoCommand
mastermind.views.UndoCommand ..> mastermind.views.MessageView
mastermind.views.UndoCommand ..> mastermind.controllers.PlayController

class mastermind.views.ProposalCommand {
    ~ ProposalCommand(controller: PlayController)
}
mastermind.views.Command <|-- mastermind.views.ProposalCommand
mastermind.views.ProposalCommand ..> mastermind.views.ProposedCombinationView
mastermind.views.ProposalCommand ..> mastermind.controllers.PlayController
mastermind.views.ProposalCommand ..> mastermind.views.MessageView

class mastermind.views.PlayMenu {
    ~ PlayMenu(controller: PlayController)
}
mastermind.utils.Menu <|--- mastermind.views.PlayMenu
mastermind.views.PlayMenu ..> mastermind.controllers.PlayController
mastermind.views.PlayMenu *--> mastermind.views.ProposalCommand
mastermind.views.PlayMenu *--> mastermind.views.UndoCommand
mastermind.views.PlayMenu *--> mastermind.views.RedoCommand

class mastermind.views.PlayView {
    + interact(controller: PlayController): void
}
mastermind.views.PlayView ..> mastermind.views.PlayMenu
mastermind.views.PlayView ..> mastermind.views.BoardView

class mastermind.views.ResultView {
    ~ writeln(int): void
}
utils.WithConsoleView <|-- mastermind.views.ResultView
mastermind.views.ResultView ..> mastermind.views.MessageView

class mastermind.views.ResumeView {
    ~ interact(controller: ResumeController): void
}
mastermind.views.ResumeView ..> mastermind.controllers.ResumeController
mastermind.views.ResumeView ..> utils.YesNoDialog
mastermind.views.ResumeView ..> mastermind.views.MessageView

class mastermind.views.StartView {
    ~ interact(controller: StartController): void
}
utils.WithConsoleView <|-- mastermind.views.StartView
mastermind.views.StartView ..> mastermind.controllers.StartController
mastermind.views.StartView ..> mastermind.views.MessageView

class mastermind.views.View {
    - startView: StartView
    - proposalView: ProposalView
    - resumeView: ResumeView
    + View()
    + interact(controller: AcceptorController): void
    + visit(controller: StartController): void
    + visit(controller: PlayController): void
    + visit(controller: ResumeController): void
}
mastermind.controllers.ControllerVisitor <|.. mastermind.views.View
mastermind.views.View ..> mastermind.controllers.AcceptorController
mastermind.views.View ..> mastermind.controllers.PlayController
mastermind.views.View *--> mastermind.views.StartView
mastermind.views.View *--> mastermind.views.PlayView
mastermind.views.View *--> mastermind.views.ResumeView

interface mastermind.controllers.AcceptorController { }
interface mastermind.controllers.ControllerVisitor { }

abstract class mastermind.controllers.Controller {
    ~ session: Session
    + View(Session)
}
mastermind.controllers.PlayController ---> mastermind.models.Session
mastermind.controllers.Controller *--> mastermind.models.Session

class mastermind.controllers.RedoController {
    ~ redo(): void
    ~ isRedoable(): boolean
}
mastermind.controllers.Controller <|-- mastermind.controllers.RedoController

class mastermind.controllers.UndoController {
    ~ undo(): void
    ~ isUndoable(): boolean
}
mastermind.controllers.Controller <|-- mastermind.controllers.UndoController

class mastermind.controllers.ProposalController {
    ~ getAttempts() : int
    ~ addProposedCombination() : void
    ~ isWinner() : boolean
    ~ isLooser() : boolean
    ~ isFinished() : boolean
    ~ getProposedCombination(pos: int) : ProposedCombination
    ~ getResult(pos: int) : Result
}
mastermind.controllers.Controller <|-- mastermind.controllers.ProposalController

class mastermind.controllers.PlayController {
    ~ undo(): void
    ~ isUndoable(): boolean
}
mastermind.controllers.Controller <|-- mastermind.controllers.PlayController
mastermind.controllers.AcceptorController <|.. mastermind.controllers.PlayController
mastermind.controllers.PlayController *--> mastermind.controllers.UndoController
mastermind.controllers.PlayController *--> mastermind.controllers.RedoController
mastermind.controllers.PlayController *--> mastermind.controllers.ProposalController

class mastermind.models.Session {
    - mastermind: Mastermind
    - registry: GameRegistry
    - state: State
    + Session()
}
mastermind.models.Session *--> mastermind.models.Mastermind
mastermind.models.Session *--> mastermind.models.GameRegistry
mastermind.models.Session *--> mastermind.models.State

class mastermind.models.GameRegistry {
   - mementos: List<GameMemento>
   - mastermind: Mastermind
   - actualIndex: int
   ~ GameRegistry(Mastermind)
   ~ register(): void
   ~ undo(): void
   ~ redo(): void
   ~ isUndoable(): boolean
   ~ isRedoable(): boolean
}
mastermind.models.GameRegistry *--> mastermind.models.GameMemento
mastermind.models.GameRegistry --> mastermind.models.Mastermind

class mastermind.models.Mastermind {
   ~ createMemento(): GameMemento
   ~ restore(GameMemento): void
}
mastermind.models.Mastermind ..> mastermind.models.GameMemento

class mastermind.models.GameMemento {
   - proposedCombinations: List<ProposedCombination>
   - results: List<Result>
   - attempts: int
   ~ GameMemento(proposedCombinations, results, attempts)
}

class mastermind.views.BoardView {
   ~ write(PlayController): void
}
mastermind.views.BoardView --> mastermind.controllers.PlayController
mastermind.views.BoardView ..> mastermind.views.ResultView

class mastermind.controllers.ResumeController {
   ~ ResumeController(Session)
   ~ resume(newGame): void
}
mastermind.controllers.AcceptorController <|.. mastermind.controllers.ResumeController
mastermind.controllers.Controller <|-- mastermind.controllers.ResumeController
mastermind.controllers.ResumeController ..> mastermind.controllers.ControllerVisitor

class mastermind.controllers.StartController {
   ~ StartController(Session)
}
mastermind.controllers.AcceptorController <|.. mastermind.controllers.StartController
mastermind.controllers.Controller <|-- mastermind.controllers.StartController

class mastermind.distributed.MastermindServer {
    - dispatcherRegistry: DispatcherRegistry
    - logic: ServerLogic
    + {static} main() : void
}
mastermind.distributed.MastermindServer <|-- mastermind.MastermindStarter
mastermind.distributed.MastermindServer *--> mastermind.distributed.dispatchers.DispatcherRegistry
mastermind.distributed.MastermindServer *--> mastermind.distributed.ServerLogic

class mastermind.distributed.ServerLogic {
    + createDispatchers(DispatcherRegistry): void
}
mastermind.distributed.MastermindServer ..> mastermind.distributed.dispatchers.FrameType

class mastermind.distributed.dispatchers.DispatcherRegistry {
    - tcpip: TCPIP
    - dispatchers: Map<FrameType, Dispatcher>
    + add(FrameType, Dispatcher): void
    + serve(): void
}

class mastermind.distributed.MastermindClient {
    - logic: LogicProxy
    # play() : void
    + {static} main() : void
}
mastermind.MastermindStarter <|-- mastermind.distributed.MastermindClient
mastermind.distributed.MastermindClient *--> mastermind.distributed.LogicProxy

class mastermind.distributed.LogicProxy {
    - tcpip: TCPIP
    + close(): void
}
mastermind.distributed.LogicProxy *--> mastermind.distributed.SessionProxy
mastermind.distributed.LogicProxy *--> mastermind.distributed.dispatchers.TCPIP
mastermind.distributed.LogicProxy ..> mastermind.distributed.StartControllerProxy
mastermind.distributed.LogicProxy ..> mastermind.distributed.PlayControllerProxy
mastermind.distributed.LogicProxy ..> mastermind.distributed.ResumeControllerProxy

class mastermind.distributed.SessionProxy {
    - tcpip: TCPIP
    + getValueState() : StateValue
}
mastermind.distributed.SessionProxy ..> mastermind.models.StateValue
mastermind.distributed.SessionProxy ..> mastermind.distributed.dispatchers.FrameType

class mastermind.distributed.StartControllerProxy {
    - tcpip: TCPIP
}
mastermind.controllers.StartController <|-- mastermind.distributed.StartControllerProxy
mastermind.distributed.StartControllerProxy ..> mastermind.distributed.dispatchers.FrameType

class mastermind.distributed.PlayControllerProxy {
    - tcpip: TCPIP
}
mastermind.controllers.PlayController <|-- mastermind.distributed.PlayControllerProxy
mastermind.distributed.PlayControllerProxy ..> mastermind.distributed.dispatchers.FrameType

class mastermind.distributed.ResumeControllerProxy {
    - tcpip: TCPIP
}
mastermind.controllers.ResumeController <|-- mastermind.distributed.ResumeControllerProxy
mastermind.distributed.ResumeControllerProxy ..> mastermind.distributed.dispatchers.FrameType

enum mastermind.distributed.dispatchers.FrameType {
    START,
	STATE,
	UNDO,
	REDO,
	UNDOABLE,
	REDOABLE,
	PROPOSE,
	CLOSE,
	FINISHED,
	CONTINUE_STATE,
	NEW_GAME
}


@enduml