@startuml

top to bottom direction

!include mastermind.controllers.puml
!include mastermind.distributed.puml
!include mastermind.models.puml
!include mastermind.views.puml

abstract class mastermind.MastermindStarter {
    - logic: Logic
    - view: View
    # {abstract} createLogic(): Logic
    # {abstract} createView(): MastermindView
    # play(): void
}
mastermind.MastermindStarter --> mastermind.controllers.Logic
mastermind.MastermindStarter --> mastermind.views.MastermindView
mastermind.MastermindStarter ..> mastermind.controllers.AcceptorController

class mastermind.MastermindStandalone {
    # createLogic(): Logic
    # createView(): Logic
    + {static} main(): void
}
mastermind.MastermindStarter <|-- mastermind.MastermindStandalone
mastermind.MastermindStandalone ..> mastermind.controllers.implementation.LogicImplementation

@enduml